const adjectives = [
	"Adorable",
	"Adventurous",
	"Aggressive",
	"Agreeable",
	"Alert",
	"Alive",
	"Amused",
	"Angry",
	"Annoyed",
	"Annoying",
	"Anxious",
	"Arrogant",
	"Ashamed",
	"Attractive",
	"Average",
	"Awful",
	"Bad",
	"Beautiful",
	"Better",
	"Bewildered",
	"Black",
	"Bloody",
	"Blue",
	"Blushing",
	"Bored",
	"Brainy",
	"Brave",
	"Breakable",
	"Bright",
	"Busy",
	"Calm",
	"Careful",
	"Cautious",
	"Charming",
	"Cheerful",
	"Clean",
	"Clear",
	"Clever",
	"Cloudy",
	"Clumsy",
	"Colorful",
	"Combative",
	"Comfortable",
	"Concerned",
	"Condemned",
	"Confused",
	"Cooperative",
	"Courageous",
	"Crazy",
	"Creepy",
	"Crowded",
	"Cruel",
	"Curious",
	"Cute",
	"Dangerous",
	"Dark",
	"Dead",
	"Defeated",
	"Defiant",
	"Delightful",
	"Depressed",
	"Determined",
	"Different",
	"Difficult",
	"Disgusted",
	"Distinct",
	"Disturbed",
	"Dizzy",
	"Doubtful",
	"Drab",
	"Dull",
	"Eager",
	"Easy",
	"Elated",
	"Elegant",
	"Embarrassed",
	"Enchanting",
	"Encouraging",
	"Energetic",
	"Enthusiastic",
	"Envious",
	"Evil",
	"Excited",
	"Expensive",
	"Exuberant",
	"Fair",
	"Faithful",
	"Famous",
	"Fancy",
	"Fantastic",
	"Fierce",
	"Filthy",
	"Fine",
	"Foolish",
	"Fragile",
	"Frail",
	"Frantic",
	"Friendly",
	"Frightened",
	"Gentle",
	"Gifted",
	"Glamorous",
	"Gleaming",
	"Glorious",
	"Good",
	"Gorgeous",
	"Graceful",
	"Grieving",
	"Grotesque",
	"Grumpy",
	"Handsome",
	"Happy",
	"Healthy",
	"Helpful",
	"Helpless",
	"Hilarious",
	"Homeless",
	"Homely",
	"Horrible",
	"Hungry",
	"Hurt",
	"Ill",
	"Important",
	"Impossible",
	"Inexpensive",
	"Innocent",
	"Inquisitive",
	"Itchy",
	"Jealous",
	"Jittery",
	"Jolly",
	"Joyous",
	"Kind",
	"Lazy",
	"Light",
	"Lively",
	"Lonely",
	"Long",
	"Lovely",
	"Lucky",
	"Magnificent",
	"Misty",
	"Modern",
	"Motionless",
	"Muddy",
	"Mushy",
	"Mysterious",
	"Nasty",
	"Naughty",
	"Nervous",
	"Nice",
	"Nutty",
	"Obedient",
	"Obnoxious",
	"Odd",
	"Open",
	"Outrageous",
	"Outstanding",
	"Panicky",
	"Perfect",
	"Plain",
	"Pleasant",
	"Poised",
	"Poor",
	"Powerful",
	"Precious",
	"Prickly",
	"Proud",
	"Putrid",
	"Puzzled",
	"Quaint",
	"Real",
	"Relieved",
	"Repulsive",
	"Rich",
	"Scary",
	"Selfish",
	"Shiny",
	"Shy",
	"Silly",
	"Sleepy",
	"Smiling",
	"Smoggy",
	"Sore",
	"Sparkling",
	"Splendid",
	"Spotless",
	"Stormy",
	"Strange",
	"Stupid",
	"Successful",
	"Super",
	"Talented",
	"Tame",
	"Tasty",
	"Tender",
	"Tense",
	"Terrible",
	"Thankful",
	"Thoughtful",
	"Thoughtless",
	"Tired",
	"Tough",
	"Troubled",
	"Ugliest",
	"Ugly",
	"Uninterested",
	"Unsightly",
	"Unusual",
	"Upset",
	"Uptight",
	"Vast",
	"Victorious",
	"Vivacious",
	"Wandering",
	"Weary",
	"Wicked",
	"Wild",
	"Witty",
	"Worried",
	"Worrisome",
	"Wrong",
	"Zany",
	"Zealous",
]

const nouns = [
	"Aardwolf",
	"Ackie Monitor",
	"Addax",
	"Adélie Penguin",
	"Affenpinscher",
	"Afghan Hound",
	"African Civet",
	"African Jacana",
	"Agama Lizard",
	"Agouti",
	"Aidi",
	"Ainu",
	"Airedoodle",
	"Akbash",
	"Akita",
	"Akita Shepherd",
	"Alaskan Husky",
	"Albacore Tuna",
	"Albatross",
	"Albertonectes",
	"Alpaca",
	"Alpine Goat",
	"Alusky",
	"Amano Shrimp",
	"Amazon Parrot",
	"Amberjack",
	"American Bully",
	"American Eel",
	"American Robin",
	"American Toad",
	"Amur Leopard",
	"Anaconda",
	"Angelfish",
	"Angelshark",
	"Anglerfish",
	"Angora Ferret",
	"Angora Goat",
	"Anhinga",
	"Anole Lizard",
	"Anomalocaris",
	"Ant",
	"Anteater",
	"Antelope",
	"Ape",
	"Apennine Wolf",
	"Apple Moth",
	"Arabian Cobra",
	"Arabian Wolf",
	"Arapaima",
	"Archerfish",
	"Arctic Char",
	"Arctic Fox",
	"Arctic Hare",
	"Arctic Wolf",
	"Arctodus",
	"Arctotherium",
	"Armadillo",
	"Armenian Gampr",
	"Armyworm",
	"Asian Arowana",
	"Asian Carp",
	"Asian Elephant",
	"Asp",
	"Atlantic Cod",
	"Atlas Beetle",
	"Atlas Moth",
	"Aurochs",
	"Aussiedor",
	"Aussiepom",
	"Babirusa",
	"Baboon",
	"Bactrian Camel",
	"Badger",
	"Bagworm Moth",
	"Bald Eagle",
	"Baleen Whale",
	"Balinese",
	"Balkan Lynx",
	"Ball Python",
	"Bamboo Shark",
	"Bamboo Worms",
	"Banana Eel",
	"Banana Spider",
	"Banded Krait",
	"Bandicoot",
	"Banjo Catfish",
	"Barb",
	"Bark Beetle",
	"Bark Scorpion",
	"Barn Owl",
	"Barn Spider",
	"Barn Swallow",
	"Barnacle",
	"Barylambda",
	"Basenji Dog",
	"Basking Shark",
	"Bass",
	"Bassador",
	"Basset Hound",
	"Bassetoodle",
	"Bat",
	"Batfish",
	"Baya",
	"Beabull",
	"Beagador",
	"Beaglier",
	"Beago",
	"Bear",
	"Bearded Collie",
	"Bearded Dragon",
	"Beaski",
	"Beauceron",
	"Beaver",
	"Bed Bugs",
	"Bee",
	"Beefalo",
	"Beetle",
	"Beewolf wasp",
	"Belgian Canary",
	"Bengal Tiger",
	"Bergamasco",
	"Berger Picard",
	"Bernedoodle",
	"Bhutan Takin",
	"Bichir",
	"Bichon Frise",
	"Bichpoo",
	"Biewer Terrier",
	"Bighorn Sheep",
	"Bilby",
	"Binturong",
	"Bird",
	"Bird Snake",
	"Birman",
	"Biscuit Beetle",
	"Bison",
	"Black Aphids",
	"Black Bass",
	"Black Crappie",
	"Black Mamba",
	"Black Wasp",
	"Blackfin Tuna",
	"Blacktip Shark",
	"Blind Snake",
	"Blister Beetle",
	"Blobfish",
	"Blood Python",
	"Blowfly",
	"Boas",
	"Bobcat",
	"Bobolink",
	"Boer Goat",
	"Boerboel",
	"Boggle",
	"Boglen Terrier",
	"Boiga",
	"Bolognese Dog",
	"Bombay",
	"Bonefish",
	"Bongo",
	"Bonito Fish",
	"Bonobo",
	"Booby",
	"Boomslang",
	"Booted Bantam",
	"Borador",
	"Border Collie",
	"Border Terrier",
	"Bordoodle",
	"Borkie",
	"Boskimo",
	"Boston Terrier",
	"Bowfin",
	"Bowhead Whale",
	"Box Jellyfish",
	"Box Turtle",
	"Boxachi",
	"Boxador",
	"Boxer Dog",
	"Boxerdoodle",
	"Boxfish",
	"Boxsky",
	"Boxweiler",
	"Boykin Spaniel",
	"Brahma Chicken",
	"Briard",
	"British Timber",
	"Brook Trout",
	"Brown Bear",
	"Brown Hyena",
	"Brown Snake",
	"Brug",
	"Budgerigar",
	"Buffalo",
	"Buffalo Fish",
	"Bull Shark",
	"Bull Terrier",
	"Bull Trout",
	"Bullboxer",
	"Bulldog",
	"Bullfrog",
	"Bullmastiff",
	"Bullsnake",
	"Bumblebee",
	"Burmese",
	"Burmese Python",
	"Burrowing Frog",
	"Burrowing Owl",
	"Bush Baby",
	"Bush Viper",
	"Butterfly",
	"Butterfly Fish",
	"Cabbage Moth",
	"Cactus Moth",
	"Cactus Mouse",
	"Cactus Wren",
	"Caecilian",
	"Caiman",
	"Caiman Lizard",
	"Cairn Terrier",
	"Camel",
	"Camel Cricket",
	"Camel Spider",
	"Canaan Dog",
	"Canada Lynx",
	"Canada Warbler",
	"Canadian Horse",
	"Cane Corso",
	"Cane Rat",
	"Cane Spider",
	"Cantil",
	"Canvasback",
	"Cape Lion",
	"Capuchin",
	"Capybara",
	"Caracal",
	"Cardinal",
	"Caribou",
	"Carolina Dog",
	"Carp",
	"Carpenter Ant",
	"Carpet Beetle",
	"Carpet Python",
	"Carpet Viper",
	"Carrion Beetle",
	"Cascabel",
	"Cashmere Goat",
	"Cassowary",
	"Cat",
	"Cat Snake",
	"Caterpillar",
	"Catfish",
	"Cava Tzu",
	"Cavador",
	"Cavapoo",
	"Cave Bear",
	"Cave Lion",
	"Cecropia Moth",
	"Cedar Waxwing",
	"Cesky Fousek",
	"Cesky Terrier",
	"Chain Pickerel",
	"Chameleon",
	"Chamois",
	"Cheagle",
	"Cheetah",
	"Chi Chi",
	"Chickadee",
	"Chicken",
	"Chicken Snake",
	"Chigger",
	"Chihuahua",
	"Chimaera",
	"Chimpanzee",
	"Chinchilla",
	"Chinese Cobra",
	"Chinese Geese",
	"Chinook",
	"Chinook Salmon",
	"Chipit",
	"Chipmunk",
	"Chipoo",
	"Chiton",
	"Chiweenie",
	"Chorkie",
	"Chow Chow",
	"Chow Pom",
	"Chow Shepherd",
	"Chusky",
	"Cicada",
	"Cichlid",
	"Cinnamon Bear",
	"Click Beetle",
	"Clock Spider",
	"Clothes Moth",
	"Clownfish",
	"Coastal Taipan",
	"Coati",
	"Cobia Fish",
	"Cobras",
	"Cochin Chicken",
	"Cockalier",
	"Cockapoo",
	"Cockatiel",
	"Cockatoo",
	"Cocker Spaniel",
	"Cockle",
	"Cockroach",
	"Coconut Crab",
	"Codfish",
	"Codling Moth",
	"Coelacanth",
	"Collie",
	"Colossal Squid",
	"Comb Jellyfish",
	"Comet Moth",
	"Compsognathus",
	"Cone Snail",
	"Conger Eel",
	"Congo Snake",
	"Conure",
	"Copperhead",
	"Coral",
	"Coral Snake",
	"Corella",
	"Corkie",
	"Cormorant",
	"Corn Earworm",
	"Corn Snake",
	"Cory Catfish",
	"Coryphodon",
	"Cottonmouth",
	"Coues Deer",
	"Cougar",
	"Cow",
	"Coyote",
	"Crab",
	"Crab Spider",
	"Crabeater Seal",
	"Crane",
	"Crappie Fish",
	"Crayfish",
	"Crested Gecko",
	"Cricket",
	"Crocodile",
	"Crocodylomorph",
	"Cross Fox",
	"Crow",
	"Crucian Carp",
	"Cuban Boa",
	"Cubera Snapper",
	"Cuckoo",
	"Cuttlefish",
	"Dachsador",
	"Dachshund",
	"Daeodon",
	"Dalmadoodle",
	"Dalmador",
	"Damselfish",
	"Daniff",
	"Danios",
	"Daug",
	"Death Adder",
	"Decorator Crab",
	"Deer",
	"Deer Mouse",
	"Deer Tick",
	"Deinocheirus",
	"Deinosuchus",
	"Desert Locust",
	"Desert Wolf",
	"Devon Rex",
	"Dhole",
	"Diamond Python",
	"Dimetrodon",
	"Dingo",
	"Dinofelis",
	"Dire Wolf",
	"Disco Clam",
	"Discus",
	"Diving Duck",
	"Dobsonfly",
	"Dodo",
	"Doedicurus",
	"Dog",
	"Dog Tick",
	"Dogo Argentino",
	"Dolphin",
	"Donkey",
	"Dorgi",
	"Dorkie",
	"Dormouse",
	"Double Doodle",
	"Douc",
	"Doxiepoo",
	"Doxle",
	"Dragon Eel",
	"Dragonfish",
	"Dragonfly",
	"Dreadnoughtus",
	"Drever",
	"Drum Fish",
	"Duck",
	"Dugong",
	"Dumeril’s Boa",
	"Dung Beetle",
	"Dungeness Crab",
	"Dunker",
	"Dunkleosteus",
	"Dunnock",
	"Dusky Dolphin",
	"Dusky Shark",
	"Dutch Rabbit",
	"Dutch Shepherd",
	"Dwarf Boa",
	"Dwarf Gourami",
	"Dwarf Hamster",
	"Eagle",
	"Eagle Ray",
	"Eared Grebe",
	"Earthworm",
	"Earwig",
	"Eastern Phoebe",
	"Eastern Racer",
	"Echidna",
	"Edible Frog",
	"Eel",
	"Eel catfish",
	"Eelpout",
	"Egret",
	"Egyptian Goose",
	"Egyptian Mau",
	"Eider",
	"Eland",
	"Electric Eel",
	"Elegant Tern",
	"Elephant",
	"Elephant Bird",
	"Elephant Fish",
	"Elephant Seal",
	"Elephant Shrew",
	"Elf Owl",
	"Elk",
	"Ember Tetra",
	"Embolotherium",
	"Emperor Goose",
	"Emu",
	"English Setter",
	"Ermine",
	"Eryops",
	"Escolar",
	"Eskimo Dog",
	"Eskipoo",
	"Eurasian Jay",
	"Eurasian Lynx",
	"Eurasian Wolf",
	"Eurasier",
	"European Robin",
	"Evening Bat",
	"Eyelash Viper",
	"Fainting Goat",
	"Falcon",
	"Fallow deer",
	"Fangtooth",
	"Feather Star",
	"Feist",
	"Fennec Fox",
	"Ferret",
	"Fiddler Crab",
	"Field Spaniel",
	"Fierce Snake",
	"Fin Whale",
	"Finch",
	"Finnish Spitz",
	"Fire Eel",
	"Firefly",
	"Fish",
	"Fisher",
	"Fishing Cat",
	"Flamingo",
	"Flea",
	"Flea Beetle",
	"Florida Gar",
	"Florida Mouse",
	"Flounder",
	"Flounder Fish",
	"Flour Beetle",
	"Fly",
	"Flycatcher",
	"Flying Fish",
	"Flying Lemur",
	"Flying Snake",
	"Football Fish",
	"Forest Cobra",
	"Fossa",
	"Fox",
	"Fox Squirrel",
	"Fox Terrier",
	"French Bulldog",
	"French Lop",
	"Frenchton",
	"Frengle",
	"Frigatebird",
	"Frilled Lizard",
	"Frilled Shark",
	"Frog",
	"Frogfish",
	"Fruit Bat",
	"Fruit Fly",
	"Fur Seal",
	"Furrow Bee",
	"Gaboon Viper",
	"Gadwall",
	"Gar",
	"Garden Eel",
	"Garden Spider",
	"Gargoyle Gecko",
	"Garter Snake",
	"Gastornis",
	"Gazelle",
	"Gecko",
	"Genet",
	"Gentoo Penguin",
	"Gerbil",
	"German Sheppit",
	"German Spitz",
	"Gharial",
	"Ghost Catfish",
	"Ghost Crab",
	"Giant Beaver",
	"Giant Clam",
	"Giant Isopod",
	"Giant Trevally",
	"Giant Weta",
	"Gibbon",
	"Gila Monster",
	"Giraffe",
	"Glass Frog",
	"Glass Lizard",
	"Glechon",
	"Glowworm",
	"Gnat",
	"Goat",
	"Goberian",
	"Goblin Shark",
	"Goby Fish",
	"Goldador",
	"Goldcrest",
	"Golden Dox",
	"Goliath Beetle",
	"Goliath Frog",
	"Gollie",
	"Goonch Catfish",
	"Goose",
	"Gopher",
	"Gopher Snake",
	"Goral",
	"Gordon Setter",
	"Gorilla",
	"Goshawk",
	"Gouldian Finch",
	"Gourami",
	"Grass Carp",
	"Grass Snake",
	"Grass Spider",
	"Grasshopper",
	"Grebe",
	"Greyhound",
	"Griffonshire",
	"Grizzly Bear",
	"Groenendael",
	"Ground Snake",
	"Groundhog Tick",
	"Grouper",
	"Grouse",
	"Grunion",
	"Guadalupe Bass",
	"Guinea Fowl",
	"Guinea Pig",
	"Gulper Catfish", 
	"Guppy",
	"Haast’s Eagle",
	"Habu Snake",
	"Haddock",
	"Hagfish",
	"Haikouichthys",
	"Hairy Frogfish",
	"Halibut",
	"Hallucigenia",
	"Hamster",
	"Harbor Seal",
	"Hare",
	"Harp Seal",
	"Harpy Eagle",
	"Harrier",
	"Harris’s Hawk",
	"Hartebeest",
	"Havamalt",
	"Havanese",
	"Havapoo",
	"Havashire",
	"Havashu",
	"Hawaiian Crow",
	"Hawk",
	"Hedgehog",
	"Helicoprion",
	"Hellbender",
	"Hercules Moth",
	"Hermit Crab",
	"Heron",
	"Herring",
	"Herring Gull",
	"Himalayan",
	"Hippopotamus",
	"Hoary Bat",
	"Hobo Spider",
	"Hogfish",
	"Hognose snake",
	"Hokkaido",
	"Honey Badger",
	"Honey Bee",
	"Honey Buzzard",
	"Hooded Oriole",
	"Hooded Seal",
	"Hoopoe",
	"Horgi",
	"Horn Shark",
	"Hornbill",
	"Horned Adder",
	"Horned Beetle",
	"Horned Grebe",
	"Horned Lizard",
	"Horned Viper",
	"Hornet",
	"Horse",
	"Horse Mackerel",
	"Horsefly",
	"Horseshoe Crab",
	"Houdan Chicken",
	"House Finch",
	"House wren",
	"Housefly",
	"Hovawart",
	"Howler Monkey",
	"Humboldt Squid",
	"Hummingbird",
	"Humpback Whale",
	"Huntaway",
	"Huskador",
	"Huskita",
	"Husky",
	"Husky Jack",
	"Huskydoodle",
	"Hyacinth Macaw",
	"Hyaenodon",
	"Hyena",
	"Ibex",
	"Ibis",
	"Ibizan Hound",
	"Iguana",
	"Iguanodon",
	"Impala",
	"Imperial Moth",
	"Inchworm",
	"Indian Cobra",
	"Indigo Snake",
	"Indri",
	"Inland Taipan",
	"Insect",
	"Insects",
	"Io Moth",
	"Irish Doodle",
	"Irish Elk",
	"Irish Setter",
	"Irish Terrier",
	"Ivy Bee",
	"Jabiru",
	"Jacana",
	"Jack Crevalle",
	"Jack Russells",
	"Jackabee",
	"Jackal",
	"Jackdaw",
	"Jackrabbit",
	"Jagdterrier",
	"Jaguar",
	"Jamaican Boa",
	"Japanese Chin",
	"Japanese Spitz",
	"Javan Leopard",
	"Javanese",
	"Jellyfish",
	"Jerboa",
	"Jewel Beetle", 
	"John Dory",
	"Jonah Crab",
	"Joro Spider",
	"Jumping Spider",
	"Junglefowl",
	"Kagu",
	"Kai Ken",
	"Kakapo",
	"Kangaroo",
	"Kangaroo Mouse",
	"Kangaroo Rat",
	"Katydid",
	"Kea",
	"Keagle",
	"Keelback",
	"Keeshond",
	"Kelp Greenling",
	"Kestrel",
	"Keta Salmon",
	"Key Deer",
	"Khao Manee",
	"Khapra Beetle",
	"Kiang",
	"Kiko Goat",
	"Killdeer",
	"Killer Whale",
	"Killifish",
	"Kinder Goat",
	"King Cobra",
	"King Crab",
	"King Eider",
	"King Mackerel",
	"King Penguin",
	"King Quail",
	"King Salmon",
	"King Shepherd",
	"King Snake",
	"King Vulture",
	"Kingfisher",
	"Kingklip",
	"Kishu",
	"Kissing Bugs",
	"Kit Fox",
	"Kitefin Shark",
	"Kiwi",
	"Klipspringer",
	"Knifefish",
	"Knight Anole",
	"Koala",
	"Kodiak Bear",
	"Kodkod",
	"Koi Fish",
	"Kokanee Salmon",
	"Komodo Dragon",
	"Komondor",
	"Koolie",
	"Korean Jindo",
	"Kori Bustard",
	"Kouprey",
	"Kowari",
	"Krait",
	"Krill",
	"Kudu",
	"Kudzu Bug",
	"Labmaraner",
	"Labrabull",
	"Labradane",
	"Labradoodle",
	"Labraheeler",
	"Labrottie",
	"Lace Bug",
	"Lace Monitor",
	"Ladybug",
	"Ladyfish",
	"Lake Sturgeon",
	"Lake Trout",
	"LaMancha Goat",
	"Lamprey",
	"Lancetfish",
	"Larder Beetle",
	"Lazarus Lizard",
	"Leafcutter Ant",
	"Leafcutter Bee",
	"Leech",
	"Leedsichthys",
	"Lemming",
	"Lemon Shark",
	"Lemur",
	"Leonberger",
	"Leopard",
	"Leopard Cat",
	"Leopard Frog",
	"Leopard Gecko",
	"Leopard Lizard",
	"Leopard Seal",
	"Leopard Shark",
	"Lesser Jacana",
	"Lesser Scaup",
	"Lhasa Apso",
	"Lhasapoo",
	"Liger",
	"Limpet",
	"Linnet",
	"Lion",
	"Lionfish",
	"Little Penguin",
	"Livyatan",
	"Lizard",
	"Lizardfish",
	"Llama",
	"Loach",
	"Lobster",
	"Locust",
	"Longnose Gar",
	"Lorikeet",
	"Loris",
	"Lowchen",
	"Lumpfish",
	"Luna Moth",
	"Lungfish",
	"Lurcher",
	"Lykoi Cat",
	"Lynx",
	"Lyrebird",
	"Macaque",
	"Macaw",
	"Macrauchenia",
	"Madora Moth",
	"Maggot",
	"Magpie",
	"Maiasaura",
	"Maine Coon",
	"Mal Shi",
	"Malayan Civet",
	"Malayan Krait",
	"Malayan Tiger",
	"Malchi",
	"Mallard",
	"Malteagle",
	"Maltese",
	"Mamba",
	"Manatee",
	"Mandrill",
	"Maned Wolf",
	"Mangrove Snake",
	"Manta Ray",
	"Mantella Frog",
	"Marabou Stork",
	"Marans Chicken",
	"Marble Fox",
	"Margay",
	"Marine Iguana",
	"Marine Toad",
	"Markhor",
	"Marmoset",
	"Marmot",
	"Marsh Frog",
	"Mason Bee",
	"Massasauga",
	"Mastador",
	"Mastiff",
	"Mauzer",
	"May Beetle",
	"Mayan Cichlid",
	"Mayfly",
	"Meagle",
	"Mealybug",
	"Meerkat",
	"Megalania",
	"Megalodon",
	"Merganser",
	"Microraptor",
	"Miki",
	"Milk Snake",
	"Milkfish",
	"Millipede",
	"Mini Lop",
	"Mink",
	"Minke Whale",
	"Moccasin Snake",
	"Mockingbird",
	"Mojarra",
	"Mole",
	"Mole Cricket",
	"Mole Snake",
	"Mollusk",
	"Molly",
	"Mongoose",
	"Mongrel",
	"Monitor Lizard",
	"Monkey",
	"Monkfish",
	"Monocled Cobra",
	"Moon Jellyfish",
	"Moonglow Boa",
	"Moorhen",
	"Moose",
	"Moray Eel",
	"Morkie",
	"Mosquito",
	"Moth",
	"Mountain Cur",
	"Mountain Feist",
	"Mountain Lion",
	"Mourning Dove",
	"Mourning Gecko",
	"Mouse",
	"Mouse Spider",
	"Mud Snake",
	"Mudi",
	"Mudpuppy",
	"Mudskipper",
	"Mule",
	"Mule Deer",
	"Mullet Fish",
	"Muntjac",
	"Muscovy Duck",
	"Musk Deer",
	"Muskox",
	"Muskrat",
	"Myna Bird",
	"Nabarlek",
	"Naegleria",
	"Narwhal",
	"Natterjack",
	"Nebelung",
	"Needlefish",
	"Nelore Cattle",
	"Neon Tetra",
	"Newfoundland",
	"Newfypoo",
	"Newt",
	"Nguni Cattle",
	"Nicobar pigeon",
	"Nigerian Goat",
	"Night Adder",
	"Night Heron",
	"Night Snake",
	"Nightingale",
	"Nightjar",
	"Nile Crocodile",
	"Nile Monitor",
	"Nile Perch",
	"Nilgai",
	"Northern Potoo",
	"Norway Rat",
	"Nubian Goat",
	"Nudibranch",
	"Numbat",
	"Nuralagus",
	"Nurse Shark",
	"Nut Weevil",
	"Nuthatch",
	"Nutria",
	"Nyala",
	"Oak Toad",
	"Oarfish",
	"Ocean Perch",
	"Ocean Pout",
	"Ocelot",
	"Octopus",
	"Oilfish",
	"Okapi",
	"Olingo",
	"Olive Baboon",
	"Olive python",
	"Olm",
	"Olympic Marmot",
	"Onager",
	"Opabinia",
	"Opah",
	"Opossum",
	"Orange Roughy",
	"Orange Spider",
	"Orangutan",
	"Orb Weaver",
	"Orchard Oriole",
	"Oribi",
	"Ornate Bichir",
	"Oscar Fish",
	"Osprey",
	"Ostracod",
	"Ostrich",
	"Otter",
	"Otterhound",
	"Ovenbird",
	"Oviraptor",
	"Owl",
	"Owl Butterfly",
	"Ox",
	"Oxpecker",
	"Oyster",
	"Ozark Bass",
	"Paddlefish",
	"Pademelon",
	"Painted Turtle",
	"Palaeophis",
	"Palm Rat",
	"Pangolin",
	"Pantaloon Bee",
	"Panther",
	"Papillon",
	"Parakeet",
	"Parrot",
	"Parrot Snake",
	"Parrotfish",
	"Parrotlet",
	"Partridge",
	"Patagotitan",
	"Patas Monkey",
	"Pea Puffer",
	"Peacock",
	"Peagle",
	"Peekapoo",
	"Pekingese",
	"Pelagornis",
	"Pelican",
	"Penguin",
	"Peppered Moth",
	"Perch Fish",
	"Persian",
	"Pharaoh Hound",
	"Pheasant",
	"Pictus Catfish",
	"Pied Tamarin",
	"Pig",
	"Pigeon",
	"Pika",
	"Pike Fish",
	"Pine Beetle",
	"Pine Marten",
	"Pine Siskin",
	"Pine Snake",
	"Pinfish",
	"Pink Bollworm",
	"Pink Salmon",
	"Pipe Snake",
	"Pipefish",
	"Piranha",
	"Pit Bull",
	"Pit Viper",
	"Pitador",
	"Pitsky",
	"Platybelodon",
	"Pliosaur",
	"Plott Hounds",
	"Pocket Beagle",
	"Pocket Pitbull",
	"Pointer",
	"Polar Bear",
	"Polecat",
	"Polish Chicken",
	"Pollock Fish",
	"Pomapoo",
	"Pomchi",
	"Pomeagle",
	"Pomeranian",
	"Pompano Fish",
	"Pomsky",
	"Pond Skater",
	"Poochon",
	"Poodle",
	"Poogle",
	"Pool Frog",
	"Porcupine",
	"Possum",
	"Potato Beetle",
	"Potoo",
	"Potoroo",
	"Prairie Dog",
	"Prawn",
	"Praying Mantis",
	"Procoptodon",
	"Pronghorn",
	"Pudelpointer",
	"Puff Adder",
	"Pufferfish",
	"Puffin",
	"Pug",
	"Pugapoo",
	"Puggle",
	"Pugshire",
	"Puma",
	"Purple Finch",
	"Python",
	"Quagga",
	"Quahog Clam",
	"Quail",
	"Queen Snake",
	"Quetzal",
	"Quokka",
	"Quoll",
	"Rabbit",
	"Raccoon",
	"Raccoon Dog",
	"Racer Snake",
	"Ragdoll",
	"Raggle",
	"Rainbow Boa",
	"Rainbow Shark",
	"Rat",
	"Rat Snakes",
	"Rat Terrier",
	"Rattlesnake",
	"Red Aphids",
	"Red Deer",
	"Red Finch",
	"Red Fox",
	"Red Kite",
	"Red Panda",
	"Red Squirrel",
	"Red Wolf",
	"Redback Spider",
	"Redcap Chicken",
	"Redear Sunfish",
	"Redstart",
	"Reef Shark",
	"Reindeer",
	"Rex Rabbit",
	"Rhea",
	"Rhesus Macaque",
	"Rhino Beetle",
	"Rhino Viper",
	"Rhinoceros",
	"Ribbon Eel",
	"Ribbon Snake",
	"Rinkhals Snake",
	"River Otter",
	"River Turtle",
	"Roadrunner",
	"Robber Flies",
	"Robin",
	"Rock Bass",
	"Rock Crab",
	"Rock Hyrax",
	"Rock Python",
	"Rockfish",
	"Rodents",
	"Roe Deer",
	"Rooster",
	"Root Aphids",
	"Rosy Boa",
	"Rotterman",
	"Rottle",
	"Rottsky",
	"Rottweiler",
	"Rove Beetle",
	"Royal Penguin",
	"Rubber Boa",
	"Ruddy Duck",
	"Russel’s Viper",
	"Russian Blue",
	"Saanen Goat",
	"Sable",
	"Saiga",
	"Sailfish",
	"Saint Bernard",
	"Saint Shepherd",
	"Salamander",
	"Salmon",
	"Salmon Shark",
	"Saluki",
	"Sambar",
	"Samoyed",
	"Sand Cat",
	"Sand Crab",
	"Sand Dollar",
	"Sand Lizard",
	"Sand Viper",
	"Sandhill Crane",
	"Sandpiper",
	"Sandworm",
	"Saola",
	"Sapsali",
	"Sardines",
	"Sarus Crane",
	"Sauropoda",
	"Savanna Goat",
	"Savu Python",
	"Sawfish",
	"Scallops",
	"Scarlet Macaw",
	"Schapendoes",
	"Schipperke",
	"Schneagle",
	"Schnoodle",
	"Scorpion",
	"Scorpion Fish",
	"Sculpin",
	"Sea Anemone",
	"Sea Bass",
	"Sea Dragon",
	"Sea Eagle",
	"Sea Lion",
	"Sea Otter",
	"Sea Roach",
	"Sea Slug",
	"Sea Snake",
	"Sea Spider",
	"Sea Squirt",
	"Sea Trout",
	"Sea Turtle",
	"Sea Urchin",
	"Seagull",
	"Seahorse",
	"Seal",
	"Sedge Warbler",
	"Sei Whale",
	"Senegal Parrot",
	"Senepol Cattle",
	"Serval",
	"Seymouria",
	"Shark",
	"Sheep",
	"Shepkita",
	"Shepweiler",
	"Shichi",
	"Shih Poo",
	"Shih Tzu",
	"Shikoku",
	"Shiranian",
	"Shoebill Stork",
	"Shollie",
	"Shrew",
	"Shrimp",
	"Siamese",
	"Siberian",
	"Siberian Husky",
	"Siberian Ibex",
	"Siberian Tiger",
	"Siberpoo",
	"Sidewinder",
	"Sika Deer",
	"Silkie Chicken",
	"Silky Shark",
	"Silky Terrier",
	"Silver Dollar",
	"Sivatherium",
	"Skink Lizard",
	"Skipjack Tuna",
	"Skua",
	"Skunk",
	"Skye Terrier",
	"Sleeper Shark",
	"Sloth",
	"Slovak Cuvac",
	"Slow Worm",
	"Slug",
	"Snail",
	"Snailfish",
	"Snake",
	"Snook Fish",
	"Snorkie",
	"Snouted Cobra",
	"Snow Bunting",
	"Snow Crab",
	"Snow Goose",
	"Snow Leopard",
	"Snowflake Eel",
	"Snowshoe",
	"Snowshoe Hare",
	"Snowy Owl",
	"Sockeye Salmon",
	"Soldier Beetle",
	"Somali",
	"Song Sparrow",
	"Song Thrush",
	"Spadefoot Toad",
	"Spanador",
	"Spanish Goat",
	"Sparrow",
	"Sparrowhawk",
	"Speckled Trout",
	"Sperm Whale",
	"Sphynx",
	"Spider",
	"Spider Beetle",
	"Spider Monkey",
	"Spider Wasp",
	"Spinner Shark",
	"Spitting Cobra",
	"Spixs Macaw",
	"Sponge",
	"Spotted Bass",
	"Spotted Gar",
	"Springador",
	"Springbok",
	"Springerdoodle",
	"Squash Bee",
	"Squash Beetle",
	"Squid",
	"Squirrel",
	"Stabyhoun",
	"Stag Beetle",
	"Starfish",
	"Stingray",
	"Stoat",
	"Stone Crab",
	"Stonechat",
	"Stonefish",
	"Striped Bass",
	"Striped Hyena",
	"Sturgeon",
	"Suchomimus",
	"Suckerfish",
	"Sugar Glider",
	"Sultan Chicken",
	"Sumatran Tiger",
	"Summer Tanager",
	"Sun Bear",
	"Sunbeam Snake",
	"Superworm",
	"Surgeonfish",
	"Sussex Chicken",
	"Swai Fish",
	"Swallow",
	"Swan",
	"Swordfish",
	"Taco Terrier",
	"Taimen Fish",
	"Taipan",
	"Takin",
	"Tamarin",
	"Tamaskan",
	"Tang",
	"Tapir",
	"Tarantula",
	"Tarantula Hawk",
	"Tarpon",
	"Tarsier",
	"Tawny Owl",
	"Teacup Maltese",
	"Teacup Poodle",
	"Telescope Fish",
	"Tenrec",
	"Termite",
	"Terrier",
	"Terror Bird",
	"Tetra",
	"Texas Heeler",
	"Thai Ridgeback",
	"Thorny Devil",
	"Thresher Shark",
	"Thrush",
	"Thylacoleo",
	"Tiffany",
	"Tiger",
	"Tiger Beetle",
	"Tiger Moth",
	"Tiger Shark",
	"Tiger snake",
	"Tiger Trout",
	"Tiktaalik",
	"Timor python",
	"Titan Beetle",
	"Titanoboa",
	"Toadfish",
	"Tokay Gecko",
	"Torkie",
	"Tornjak",
	"Tortoise",
	"Tosa",
	"Toucan",
	"Towhee",
	"Toxodon",
	"Toy Poodle",
	"Tree Cricket",
	"Tree Frog",
	"Tree Kangaroo",
	"Tree Snake",
	"Tree swallow",
	"Treecreeper",
	"Treehopper",
	"Triggerfish",
	"Troodon",
	"Tropicbird",
	"Trout",
	"Tsetse Fly",
	"Tuatara",
	"Tully Monster",
	"Tuna",
	"Tundra Swan",
	"Turaco",
	"Turkey",
	"Turkey Vulture",
	"Turkish Angora",
	"Turnspit",
	"Turtle Frog",
	"Turtles",
	"Tussock Moth",
	"Twig Snake",
	"Uakari",
	"Underwing Moth",
	"Ural owl",
	"Urial",
	"Urutu Snake",
	"Utonagan",
	"Valley Bulldog",
	"Vampire Bat",
	"Vampire Squid",
	"Vaquita",
	"Veery",
	"Vegavis",
	"Venus Flytrap",
	"Vervet Monkey",
	"Vicuña",
	"Vine Snake",
	"Vinegaroon",
	"Viper",
	"Viper Boa",
	"Viperfish",
	"Vizsla",
	"Volcano Snail",
	"Vole",
	"Vulture",
	"Wahoo Fish",
	"Waimanu",
	"Wallaby",
	"Walleye Fish",
	"Walrus",
	"Warbler",
	"Warthog",
	"Wasp",
	"Water Beetle",
	"Water Buffalo",
	"Water Bug",
	"Water Dragon",
	"Water Vole",
	"Waterbuck",
	"Wattled Jacana",
	"Wax Moth",
	"Weasel",
	"Weaver Bird",
	"Weimaraner",
	"Weimardoodle",
	"Wels Catfish",
	"Welsh Corgi",
	"Welsh Terrier",
	"Westiepoo",
	"Whale Shark",
	"Whimbrel",
	"Whinchat",
	"Whippet",
	"White Bass",
	"White Catfish",
	"White Crappie",
	"White Marlin",
	"White Shark",
	"White Tiger",
	"Whitetail Deer",
	"Whiting",
	"Whoodle",
	"Whooping Crane",
	"Wild Boar",
	"Wildebeest",
	"Willow Warbler",
	"Winter Moth",
	"Wiwaxia",
	"Wolf",
	"Wolf Eel",
	"Wolf Snake",
	"Wolf Spider",
	"Wolffish",
	"Wolverine",
	"Woma Python",
	"Wombat",
	"Wood Bison",
	"Wood Duck",
	"Wood Frog",
	"Wood Tick",
	"Wood Turtle",
	"Woodlouse",
	"Woodpecker",
	"Woodrat",
	"Woolly Aphids",
	"Woolly Mammoth",
	"Woolly Monkey",
	"Worm",
	"Worm Snake",
	"Wrasse",
	"Writing Spider",
	"Wryneck",
	"Wyoming Toad",
	"Xerus",
	"Yabby",
	"Yak",
	"Yakutian Laika",
	"Yarara",
	"Yellowhammer",
	"Yeti Crab",
	"Yoranian",
	"Yorkie Bichon",
	"Yorkiepoo",
	"Zebra",
	"Zebra Finch",
	"Zebra Mussels",
	"Zebra Pleco",
	"Zebra Shark",
	"Zebra Snake",
	"Zebu",
	"Zokor",
	"Zonkey",
	"Zorse",
	"Zuchon",
]

function randomNumber(seed: number) {
	const mask = 0xffffffff
	let m_w  = (123456789 + seed) & mask
	let m_z  = (987654321 - seed) & mask

	m_z = (36969 * (m_z & 65535) + (m_z >>> 16)) & mask
	m_w = (18000 * (m_w & 65535) + (m_w >>> 16)) & mask

	let result = ((m_z << 16) + (m_w & 65535)) >>> 0
	result /= 4294967296

	return result
}

export function name(userId: number, ownUserId: number) {
	const random = Math.floor(randomNumber(userId + ownUserId) * Math.max(adjectives.length, nouns.length))

	const adjectiveIndex = random % adjectives.length
	const nounIndex = random % nouns.length
    
	return `${adjectives[adjectiveIndex]} ${nouns[nounIndex]}`
}